/**
 * Tangled file output handling.
 *
 * This module handles writing tangled files to disk, including:
 * - Creating directory structures
 * - Writing file contents
 * - Generating source maps (optional)
 * - Cleaning up removed files
 */

import * as fs from 'node:fs/promises';
import * as path from 'node:path';

import type { TangledFile, TangleResult } from '@repo/techbook-types';
import { z } from 'zod';

/**
 * Options for writing tangled output
 */
export interface TangleOutputOptions {
  /** Base directory for output (e.g., "build/src") */
  outputDir: string;
  /** Whether to clean files not in the tangle result */
  cleanOrphans?: boolean;
  /** File extensions to clean (default: all files) */
  cleanExtensions?: string[];
  /** Whether to generate source map comments */
  generateSourceMaps?: boolean;
  /** Whether to write a manifest file */
  writeManifest?: boolean;
  /** Whether to preserve timestamps of unchanged files */
  preserveTimestamps?: boolean;
}

/**
 * Result of writing tangled output
 */
export interface TangleOutputResult {
  /** Whether writing succeeded */
  success: boolean;
  /** Files that were written */
  writtenFiles: string[];
  /** Files that were skipped (unchanged) */
  skippedFiles: string[];
  /** Files that were cleaned up */
  cleanedFiles: string[];
  /** Errors encountered */
  errors: Array<{ file: string; message: string }>;
}

/**
 * Manifest of tangled output for tracking
 */
export interface TangleManifest {
  /** When the tangle was performed */
  tangledAt: string;
  /** Files in the output */
  files: Array<{
    path: string;
    contentHash: string;
    snippetCount: number;
  }>;
  /** Total statistics */
  stats: {
    fileCount: number;
    totalLines: number;
    totalSnippets: number;
  };
}

/**
 * Ensure directory exists for a file path
 */
async function ensureDirectory(filePath: string): Promise<void> {
  const dir = path.dirname(filePath);
  await fs.mkdir(dir, { recursive: true });
}

/**
 * Read existing file content (returns undefined if doesn't exist)
 */
async function readExistingContent(filePath: string): Promise<string | undefined> {
  try {
    return await fs.readFile(filePath, 'utf-8');
  } catch {
    return undefined;
  }
}

/**
 * Generate a source map comment for a tangled file.
 *
 * This creates a simple comment that indicates the file is generated
 * and lists the snippets that contributed to it.
 */
function generateSourceComment(file: TangledFile, language: string): string {
  const snippetList = file.sourceSnippetIds.join(', ');
  const commentStart = getCommentStart(language);
  const commentEnd = getCommentEnd(language);

  return `${commentStart} Generated by Spine TechBook - DO NOT EDIT DIRECTLY\n${commentStart} Source snippets: ${snippetList}${commentEnd}\n\n`;
}

/**
 * Get comment syntax for a language
 */
function getCommentStart(language: string): string {
  switch (language.toLowerCase()) {
    case 'html':
    case 'xml':
      return '<!-- ';
    case 'css':
      return '/* ';
    case 'python':
    case 'ruby':
    case 'bash':
    case 'shell':
    case 'sh':
      return '# ';
    default:
      return '// ';
  }
}

/**
 * Get comment end syntax for a language
 */
function getCommentEnd(language: string): string {
  switch (language.toLowerCase()) {
    case 'html':
    case 'xml':
      return ' -->';
    case 'css':
      return ' */';
    default:
      return '';
  }
}

/**
 * Infer language from file extension
 */
function inferLanguage(filePath: string): string {
  const ext = path.extname(filePath).toLowerCase();
  const langMap: Record<string, string> = {
    '.ts': 'typescript',
    '.tsx': 'typescript',
    '.js': 'javascript',
    '.jsx': 'javascript',
    '.py': 'python',
    '.rb': 'ruby',
    '.go': 'go',
    '.rs': 'rust',
    '.java': 'java',
    '.c': 'c',
    '.cpp': 'cpp',
    '.h': 'c',
    '.hpp': 'cpp',
    '.css': 'css',
    '.html': 'html',
    '.xml': 'xml',
    '.sh': 'bash',
    '.bash': 'bash',
    '.json': 'json',
    '.yaml': 'yaml',
    '.yml': 'yaml',
    '.md': 'markdown',
  };
  return langMap[ext] ?? 'text';
}

/**
 * Write a single tangled file
 */
async function writeFile(
  file: TangledFile,
  outputDir: string,
  options: TangleOutputOptions
): Promise<{ written: boolean; error?: string }> {
  const fullPath = path.join(outputDir, file.path);

  try {
    // Check if content has changed
    if (options.preserveTimestamps) {
      const existing = await readExistingContent(fullPath);
      if (existing === file.content) {
        return { written: false }; // Skip unchanged file
      }
    }

    // Prepare content
    let content = file.content;

    if (options.generateSourceMaps) {
      const language = inferLanguage(file.path);
      const comment = generateSourceComment(file, language);
      content = comment + content;
    }

    // Ensure directory exists
    await ensureDirectory(fullPath);

    // Write file
    await fs.writeFile(fullPath, content, 'utf-8');

    return { written: true };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return { written: false, error: message };
  }
}

/**
 * Get all files in a directory recursively
 */
async function getFilesRecursive(dir: string): Promise<string[]> {
  const files: string[] = [];

  try {
    const entries = await fs.readdir(dir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);

      if (entry.isDirectory()) {
        const subFiles = await getFilesRecursive(fullPath);
        files.push(...subFiles);
      } else if (entry.isFile()) {
        files.push(fullPath);
      }
    }
  } catch {
    // Directory doesn't exist, return empty
  }

  return files;
}

/**
 * Clean up files not in the tangle result
 */
async function cleanOrphanFiles(
  outputDir: string,
  tangledPaths: Set<string>,
  extensions?: string[]
): Promise<string[]> {
  const cleaned: string[] = [];
  const existingFiles = await getFilesRecursive(outputDir);

  for (const existingPath of existingFiles) {
    const relativePath = path.relative(outputDir, existingPath);

    // Skip if in tangle result
    if (tangledPaths.has(relativePath)) {
      continue;
    }

    // Skip if extension filter doesn't match
    if (extensions && extensions.length > 0) {
      const ext = path.extname(relativePath).toLowerCase();
      if (!extensions.includes(ext)) {
        continue;
      }
    }

    // Delete the orphan file
    try {
      await fs.unlink(existingPath);
      cleaned.push(relativePath);
    } catch {
      // Ignore deletion errors
    }
  }

  return cleaned;
}

/**
 * Generate manifest for the tangle output
 */
function generateManifest(result: TangleResult): TangleManifest {
  let totalLines = 0;
  let totalSnippets = 0;

  const files = result.files.map((file) => {
    const lines = file.content.split('\n').length;
    totalLines += lines;
    totalSnippets += file.sourceSnippetIds.length;

    return {
      path: file.path,
      contentHash: file.contentHash ?? '',
      snippetCount: file.sourceSnippetIds.length,
    };
  });

  return {
    tangledAt: result.tangledAt,
    files,
    stats: {
      fileCount: result.files.length,
      totalLines,
      totalSnippets,
    },
  };
}

/**
 * Write tangled files to disk
 */
export async function writeTangledFiles(
  result: TangleResult,
  options: TangleOutputOptions
): Promise<TangleOutputResult> {
  const { outputDir, cleanOrphans, cleanExtensions, writeManifest } = options;
  const writtenFiles: string[] = [];
  const skippedFiles: string[] = [];
  const errors: Array<{ file: string; message: string }> = [];

  // Ensure output directory exists
  await fs.mkdir(outputDir, { recursive: true });

  // Write each file
  const tangledPaths = new Set<string>();

  for (const file of result.files) {
    tangledPaths.add(file.path);

    const writeResult = await writeFile(file, outputDir, options);

    if (writeResult.error) {
      errors.push({ file: file.path, message: writeResult.error });
    } else if (writeResult.written) {
      writtenFiles.push(file.path);
    } else {
      skippedFiles.push(file.path);
    }
  }

  // Clean orphan files if requested
  let cleanedFiles: string[] = [];
  if (cleanOrphans) {
    cleanedFiles = await cleanOrphanFiles(outputDir, tangledPaths, cleanExtensions);
  }

  // Write manifest if requested
  if (writeManifest) {
    const manifest = generateManifest(result);
    const manifestPath = path.join(outputDir, '.tangle-manifest.json');
    await fs.writeFile(manifestPath, JSON.stringify(manifest, null, 2), 'utf-8');
  }

  return {
    success: errors.length === 0,
    writtenFiles,
    skippedFiles,
    cleanedFiles,
    errors,
  };
}

/**
 * Schema for manifest validation
 */
const TangleManifestSchema = z.object({
  tangledAt: z.string(),
  files: z.array(z.object({
    path: z.string(),
    contentHash: z.string(),
    snippetCount: z.number(),
  })),
  stats: z.object({
    fileCount: z.number(),
    totalLines: z.number(),
    totalSnippets: z.number(),
  }),
});

/**
 * Read a previously written manifest.
 *
 * Returns null if the manifest doesn't exist or is invalid.
 */
export async function readManifest(outputDir: string): Promise<TangleManifest | null> {
  const manifestPath = path.join(outputDir, '.tangle-manifest.json');

  try {
    const content = await fs.readFile(manifestPath, 'utf-8');
    const parsed = JSON.parse(content) as unknown;
    const result = TangleManifestSchema.safeParse(parsed);

    if (!result.success) {
      return null;
    }

    return result.data;
  } catch {
    return null;
  }
}

/**
 * Compare current tangle result with previous manifest
 */
export interface ManifestComparison {
  /** Files that are new */
  added: string[];
  /** Files that were removed */
  removed: string[];
  /** Files that changed (different hash) */
  changed: string[];
  /** Files that are unchanged */
  unchanged: string[];
}

export function compareWithManifest(
  result: TangleResult,
  manifest: TangleManifest
): ManifestComparison {
  const currentFiles = new Map<string, string>();
  for (const file of result.files) {
    currentFiles.set(file.path, file.contentHash ?? '');
  }

  const previousFiles = new Map<string, string>();
  for (const file of manifest.files) {
    previousFiles.set(file.path, file.contentHash);
  }

  const added: string[] = [];
  const removed: string[] = [];
  const changed: string[] = [];
  const unchanged: string[] = [];

  // Check current files
  for (const [path, hash] of currentFiles) {
    const previousHash = previousFiles.get(path);
    if (previousHash === undefined) {
      added.push(path);
    } else if (previousHash !== hash) {
      changed.push(path);
    } else {
      unchanged.push(path);
    }
  }

  // Check for removed files
  for (const path of previousFiles.keys()) {
    if (!currentFiles.has(path)) {
      removed.push(path);
    }
  }

  return { added, removed, changed, unchanged };
}

/**
 * Delete all output files
 */
export async function cleanOutputDirectory(outputDir: string): Promise<string[]> {
  const cleaned: string[] = [];
  const files = await getFilesRecursive(outputDir);

  for (const file of files) {
    const relativePath = path.relative(outputDir, file);
    try {
      await fs.unlink(file);
      cleaned.push(relativePath);
    } catch {
      // Ignore errors
    }
  }

  return cleaned;
}

/**
 * Check if output directory exists and has files
 */
export async function hasOutputFiles(outputDir: string): Promise<boolean> {
  try {
    const files = await getFilesRecursive(outputDir);
    return files.length > 0;
  } catch {
    return false;
  }
}
