// Re-export framework types for convenience
export {
  IdSchema,
  TimestampSchema,
  EntityRefSchema,
  CrossReferenceSchema,
  SpinePositionSchema,
  BaseEntitySchema,
  BaseContentStatusSchema,
  ReferenceSchema,
  BaseContentSchema,
  ValidationPhaseSchema,
  ValidationResultSchema,
  validTransitions,
  canTransition,
  getValidNextStatuses,
  isTerminalStatus,
  canModify,
  getPreviousStatus,
  getNextStatus,
  type Id,
  type Timestamp,
  type EntityRef,
  type CrossReference,
  type Result,
  type SpinePosition,
  type BaseEntity,
  type BaseContentStatus,
  type Reference,
  type BaseContent,
  type Spine,
  type TreeSpine,
  type MutableSpine,
  type ValidationPhase,
  type ValidationResult,
  type Validator,
  type ValidatorRegistry,
} from '@repo/framework-types';

// Concept types
export {
  ConceptTypeSchema,
  ConceptExampleSchema,
  SymbolLinkSchema,
  ConceptSchema,
  ConceptSummarySchema,
  ConceptViolationSchema,
  ConceptDependencySchema,
  ConceptValidationResultSchema,
  type ConceptType,
  type ConceptExample,
  type SymbolLink,
  type Concept,
  type ConceptSummary,
  type ConceptViolation,
  type ConceptDependency,
  type ConceptValidationResult,
} from './concept';

// Snippet types
export {
  SnippetOperationSchema,
  FilePartSchema,
  SnippetSchema,
  SnippetSummarySchema,
  TangledFileSchema,
  TangleResultSchema,
  SnippetHistoryEntrySchema,
  FileEvolutionSchema,
  type SnippetOperation,
  type FilePart,
  type Snippet,
  type SnippetSummary,
  type TangledFile,
  type TangleResult,
  type SnippetHistoryEntry,
  type FileEvolution,
} from './snippet';

// Checkpoint types
export {
  CheckpointStatusSchema,
  CompileResultSchema,
  TestResultSchema,
  CheckpointSchema,
  CheckpointSummarySchema,
  CheckpointSnapshotSchema,
  CheckpointValidationResultSchema,
  type CheckpointStatus,
  type CompileResult,
  type TestResult,
  type Checkpoint,
  type CheckpointSummary,
  type CheckpointSnapshot,
  type CheckpointValidationResult,
} from './checkpoint';

// Expected output types
export {
  OutputTypeSchema,
  ComparatorTypeSchema,
  ExpectedOutputSchema,
  OutputComparisonSchema,
  OutputValidationResultSchema,
  ExpectedOutputSummarySchema,
  type OutputType,
  type ComparatorType,
  type ExpectedOutput,
  type OutputComparison,
  type OutputValidationResult,
  type ExpectedOutputSummary,
} from './output';
