/**
 * Protocol module exports - JSON-RPC 2.0 style message types and schemas.
 */

// Core types
export {
  JSONRPC_VERSION,
  MessageIdSchema,
  type MessageId,
  ErrorCode,
  type ErrorCodeType,
  RpcErrorSchema,
  type RpcError,
  API_METHODS,
  type ApiMethod,
  SUBSCRIPTION_CHANNELS,
  type SubscriptionChannel
} from './types';

// Request schemas
export {
  BaseRequestSchema,
  type BaseRequest,
  validateRequest,
  // Project
  ProjectCreateParamsSchema,
  type ProjectCreateParams,
  ProjectLoadParamsSchema,
  type ProjectLoadParams,
  ProjectDeleteParamsSchema,
  type ProjectDeleteParams,
  ProjectUpdateSettingsParamsSchema,
  type ProjectUpdateSettingsParams,
  ProjectUpdateMetadataParamsSchema,
  type ProjectUpdateMetadataParams,
  // Bible
  BibleGetParamsSchema,
  type BibleGetParams,
  BibleEntityListParamsSchema,
  type BibleEntityListParams,
  BibleEntityGetParamsSchema,
  type BibleEntityGetParams,
  BibleCharacterCreateParamsSchema,
  type BibleCharacterCreateParams,
  BibleCharacterUpdateParamsSchema,
  type BibleCharacterUpdateParams,
  BibleEntityDeleteParamsSchema,
  type BibleEntityDeleteParams,
  BibleLocationCreateParamsSchema,
  type BibleLocationCreateParams,
  BibleLocationUpdateParamsSchema,
  type BibleLocationUpdateParams,
  BibleFactionCreateParamsSchema,
  type BibleFactionCreateParams,
  BibleFactionUpdateParamsSchema,
  type BibleFactionUpdateParams,
  BibleWorldRuleCreateParamsSchema,
  type BibleWorldRuleCreateParams,
  BibleWorldRuleUpdateParamsSchema,
  type BibleWorldRuleUpdateParams,
  BiblePlotThreadCreateParamsSchema,
  type BiblePlotThreadCreateParams,
  BiblePlotThreadUpdateParamsSchema,
  type BiblePlotThreadUpdateParams,
  BibleTimelineEventCreateParamsSchema,
  type BibleTimelineEventCreateParams,
  BibleTimelineEventUpdateParamsSchema,
  type BibleTimelineEventUpdateParams,
  // Structure
  StructureGetTreeParamsSchema,
  type StructureGetTreeParams,
  StructureGetAllParamsSchema,
  type StructureGetAllParams,
  StructureGetParamsSchema,
  type StructureGetParams,
  StructureCreateParamsSchema,
  type StructureCreateParams,
  StructureUpdateParamsSchema,
  type StructureUpdateParams,
  StructureDeleteParamsSchema,
  type StructureDeleteParams,
  StructureReorderParamsSchema,
  type StructureReorderParams,
  StructureAddBeatParamsSchema,
  type StructureAddBeatParams,
  StructureRemoveBeatParamsSchema,
  type StructureRemoveBeatParams,
  StructureSetHookParamsSchema,
  type StructureSetHookParams,
  // Content
  ContentGetParamsSchema,
  type ContentGetParams,
  ContentSaveParamsSchema,
  type ContentSaveParams,
  ContentGetHistoryParamsSchema,
  type ContentGetHistoryParams,
  ContentRollbackParamsSchema,
  type ContentRollbackParams,
  // Generation
  GenerationStartParamsSchema,
  type GenerationStartParams,
  GenerationCancelParamsSchema,
  type GenerationCancelParams,
  GenerationStatusParamsSchema,
  type GenerationStatusParams,
  GenerationRetryParamsSchema,
  type GenerationRetryParams,
  // Review
  ReviewQueueParamsSchema,
  type ReviewQueueParams,
  ReviewGetItemParamsSchema,
  type ReviewGetItemParams,
  ReviewSubmitActionParamsSchema,
  type ReviewSubmitActionParams,
  ReviewBulkApproveParamsSchema,
  type ReviewBulkApproveParams,
  ReviewCreateLockPointParamsSchema,
  type ReviewCreateLockPointParams,
  ReviewPreviewCascadeParamsSchema,
  type ReviewPreviewCascadeParams,
  ReviewExecuteCascadeParamsSchema,
  type ReviewExecuteCascadeParams,
  // Analytics
  AnalyticsScopeParamsSchema,
  type AnalyticsScopeParams,
  // Serial
  SerialBufferStatusParamsSchema,
  type SerialBufferStatusParams,
  SerialReleaseScheduleParamsSchema,
  type SerialReleaseScheduleParams,
  SerialHookPatternsParamsSchema,
  type SerialHookPatternsParams,
  SerialCycleStatusParamsSchema,
  type SerialCycleStatusParams,
  SerialMysteryBoardParamsSchema,
  type SerialMysteryBoardParams,
  // Subscription
  SubscribeParamsSchema,
  type SubscribeParams,
  UnsubscribeParamsSchema,
  type UnsubscribeParams
} from './request';

// Response schemas
export {
  SuccessResponseSchema,
  type SuccessResponse,
  ErrorResponseSchema,
  type ErrorResponse,
  ResponseSchema,
  type Response,
  NotificationSchema,
  type Notification,
  createSuccessResponse,
  createErrorResponse,
  createNotification,
  SuccessResultSchema,
  type SuccessResult,
  IdResultSchema,
  type IdResult,
  GenerationIdResultSchema,
  type GenerationIdResult,
  GenerationProgressParamsSchema,
  type GenerationProgressParams,
  GenerationCompleteParamsSchema,
  type GenerationCompleteParams,
  GenerationErrorParamsSchema,
  type GenerationErrorParams,
  EntityUpdatedParamsSchema,
  type EntityUpdatedParams
} from './response';
